package com.dpc.model;

import java.util.Date;

public class DailyInfo extends DailyInfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_info.SHIFT_USER
	 * @mbggenerated
	 */
	private String shiftUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_info.CREATE_USER_ID
	 * @mbggenerated
	 */
	private String createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_info.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_info.SHIFT_USER
	 * @return  the value of daily_info.SHIFT_USER
	 * @mbggenerated
	 */
	public String getShiftUser() {
		return shiftUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_info.SHIFT_USER
	 * @param shiftUser  the value for daily_info.SHIFT_USER
	 * @mbggenerated
	 */
	public void setShiftUser(String shiftUser) {
		this.shiftUser = shiftUser == null ? null : shiftUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_info.CREATE_USER_ID
	 * @return  the value of daily_info.CREATE_USER_ID
	 * @mbggenerated
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_info.CREATE_USER_ID
	 * @param createUserId  the value for daily_info.CREATE_USER_ID
	 * @mbggenerated
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId == null ? null : createUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_info.CREATE_TIME
	 * @return  the value of daily_info.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_info.CREATE_TIME
	 * @param createTime  the value for daily_info.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}