package com.dpc.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class DailyReport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.REPORT_ID
	 * @mbggenerated
	 */
	private String reportId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.SHIFT_DATE
	 * @mbggenerated
	 */
	private Date shiftDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.SHIFT
	 * @mbggenerated
	 */
	private Long shift;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.SHOP
	 * @mbggenerated
	 */
	private Long shop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.QUESTION_TITLE
	 * @mbggenerated
	 */
	private String questionTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.QUESTION_TYPE
	 * @mbggenerated
	 */
	private Long questionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.QUESTION_USER
	 * @mbggenerated
	 */
	private String questionUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.QUESTION_CONTACT
	 * @mbggenerated
	 */
	private Long questionContact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.QUESTION_PHONE
	 * @mbggenerated
	 */
	private String questionPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.QUESTION_DETAIL
	 * @mbggenerated
	 */
	private String questionDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.QUESTION_STATE
	 * @mbggenerated
	 */
	private Long questionState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.QUESTION_REASON
	 * @mbggenerated
	 */
	private String questionReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.RECEIVE_TIME
	 * @mbggenerated
	 */
	private Date receiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.RECEIVE_USER
	 * @mbggenerated
	 */
	private String receiveUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.ANSWER_TIME
	 * @mbggenerated
	 */
	private Date answerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.ANSWER_TYPE
	 * @mbggenerated
	 */
	private Long answerType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.ANSWER_USER
	 * @mbggenerated
	 */
	private String answerUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.ANSWER_DETAIL
	 * @mbggenerated
	 */
	private String answerDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.CREATE_USER_ID
	 * @mbggenerated
	 */
	private String createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column daily_report.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.REPORT_ID
	 * @return  the value of daily_report.REPORT_ID
	 * @mbggenerated
	 */
	public String getReportId() {
		return reportId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.REPORT_ID
	 * @param reportId  the value for daily_report.REPORT_ID
	 * @mbggenerated
	 */
	public void setReportId(String reportId) {
		this.reportId = reportId == null ? null : reportId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.SHIFT_DATE
	 * @param shiftDate  the value for daily_report.SHIFT_DATE
	 * @mbggenerated
	 */
	public void setShiftDate(Date shiftDate) {
		this.shiftDate = shiftDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.SHIFT
	 * @return  the value of daily_report.SHIFT
	 * @mbggenerated
	 */
	public Long getShift() {
		return shift;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.SHIFT
	 * @param shift  the value for daily_report.SHIFT
	 * @mbggenerated
	 */
	public void setShift(Long shift) {
		this.shift = shift;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.SHOP
	 * @return  the value of daily_report.SHOP
	 * @mbggenerated
	 */
	public Long getShop() {
		return shop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.SHOP
	 * @param shop  the value for daily_report.SHOP
	 * @mbggenerated
	 */
	public void setShop(Long shop) {
		this.shop = shop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.QUESTION_TITLE
	 * @return  the value of daily_report.QUESTION_TITLE
	 * @mbggenerated
	 */
	public String getQuestionTitle() {
		return questionTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.QUESTION_TITLE
	 * @param questionTitle  the value for daily_report.QUESTION_TITLE
	 * @mbggenerated
	 */
	public void setQuestionTitle(String questionTitle) {
		this.questionTitle = questionTitle == null ? null : questionTitle
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.QUESTION_TYPE
	 * @return  the value of daily_report.QUESTION_TYPE
	 * @mbggenerated
	 */
	public Long getQuestionType() {
		return questionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.QUESTION_TYPE
	 * @param questionType  the value for daily_report.QUESTION_TYPE
	 * @mbggenerated
	 */
	public void setQuestionType(Long questionType) {
		this.questionType = questionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.QUESTION_USER
	 * @return  the value of daily_report.QUESTION_USER
	 * @mbggenerated
	 */
	public String getQuestionUser() {
		return questionUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.QUESTION_USER
	 * @param questionUser  the value for daily_report.QUESTION_USER
	 * @mbggenerated
	 */
	public void setQuestionUser(String questionUser) {
		this.questionUser = questionUser == null ? null : questionUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.QUESTION_CONTACT
	 * @return  the value of daily_report.QUESTION_CONTACT
	 * @mbggenerated
	 */
	public Long getQuestionContact() {
		return questionContact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.QUESTION_CONTACT
	 * @param questionContact  the value for daily_report.QUESTION_CONTACT
	 * @mbggenerated
	 */
	public void setQuestionContact(Long questionContact) {
		this.questionContact = questionContact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.QUESTION_PHONE
	 * @return  the value of daily_report.QUESTION_PHONE
	 * @mbggenerated
	 */
	public String getQuestionPhone() {
		return questionPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.QUESTION_PHONE
	 * @param questionPhone  the value for daily_report.QUESTION_PHONE
	 * @mbggenerated
	 */
	public void setQuestionPhone(String questionPhone) {
		this.questionPhone = questionPhone == null ? null : questionPhone
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.QUESTION_DETAIL
	 * @return  the value of daily_report.QUESTION_DETAIL
	 * @mbggenerated
	 */
	public String getQuestionDetail() {
		return questionDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.QUESTION_DETAIL
	 * @param questionDetail  the value for daily_report.QUESTION_DETAIL
	 * @mbggenerated
	 */
	public void setQuestionDetail(String questionDetail) {
		this.questionDetail = questionDetail == null ? null : questionDetail
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.QUESTION_STATE
	 * @return  the value of daily_report.QUESTION_STATE
	 * @mbggenerated
	 */
	public Long getQuestionState() {
		return questionState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.QUESTION_STATE
	 * @param questionState  the value for daily_report.QUESTION_STATE
	 * @mbggenerated
	 */
	public void setQuestionState(Long questionState) {
		this.questionState = questionState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.QUESTION_REASON
	 * @return  the value of daily_report.QUESTION_REASON
	 * @mbggenerated
	 */
	public String getQuestionReason() {
		return questionReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.QUESTION_REASON
	 * @param questionReason  the value for daily_report.QUESTION_REASON
	 * @mbggenerated
	 */
	public void setQuestionReason(String questionReason) {
		this.questionReason = questionReason == null ? null : questionReason
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.RECEIVE_TIME
	 * @return  the value of daily_report.RECEIVE_TIME
	 * @mbggenerated
	 */
	public Date getReceiveTime() {
		return receiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.RECEIVE_TIME
	 * @param receiveTime  the value for daily_report.RECEIVE_TIME
	 * @mbggenerated
	 */
	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.RECEIVE_USER
	 * @return  the value of daily_report.RECEIVE_USER
	 * @mbggenerated
	 */
	public String getReceiveUser() {
		return receiveUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.RECEIVE_USER
	 * @param receiveUser  the value for daily_report.RECEIVE_USER
	 * @mbggenerated
	 */
	public void setReceiveUser(String receiveUser) {
		this.receiveUser = receiveUser == null ? null : receiveUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.ANSWER_TIME
	 * @return  the value of daily_report.ANSWER_TIME
	 * @mbggenerated
	 */
	public Date getAnswerTime() {
		return answerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.ANSWER_TIME
	 * @param answerTime  the value for daily_report.ANSWER_TIME
	 * @mbggenerated
	 */
	public void setAnswerTime(Date answerTime) {
		this.answerTime = answerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.ANSWER_TYPE
	 * @return  the value of daily_report.ANSWER_TYPE
	 * @mbggenerated
	 */
	public Long getAnswerType() {
		return answerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.ANSWER_TYPE
	 * @param answerType  the value for daily_report.ANSWER_TYPE
	 * @mbggenerated
	 */
	public void setAnswerType(Long answerType) {
		this.answerType = answerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.ANSWER_USER
	 * @return  the value of daily_report.ANSWER_USER
	 * @mbggenerated
	 */
	public String getAnswerUser() {
		return answerUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.ANSWER_USER
	 * @param answerUser  the value for daily_report.ANSWER_USER
	 * @mbggenerated
	 */
	public void setAnswerUser(String answerUser) {
		this.answerUser = answerUser == null ? null : answerUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.ANSWER_DETAIL
	 * @return  the value of daily_report.ANSWER_DETAIL
	 * @mbggenerated
	 */
	public String getAnswerDetail() {
		return answerDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.ANSWER_DETAIL
	 * @param answerDetail  the value for daily_report.ANSWER_DETAIL
	 * @mbggenerated
	 */
	public void setAnswerDetail(String answerDetail) {
		this.answerDetail = answerDetail == null ? null : answerDetail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.CREATE_USER_ID
	 * @return  the value of daily_report.CREATE_USER_ID
	 * @mbggenerated
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.CREATE_USER_ID
	 * @param createUserId  the value for daily_report.CREATE_USER_ID
	 * @mbggenerated
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId == null ? null : createUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column daily_report.CREATE_TIME
	 * @return  the value of daily_report.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column daily_report.CREATE_TIME
	 * @param createTime  the value for daily_report.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@DateTimeFormat(pattern="yyyy-MM-dd")
	@JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
	public Date getShiftDate() {
		return shiftDate;
	}

	private String realName;
	private String saveName;
	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getSaveName() {
		return saveName;
	}

	public void setSaveName(String saveName) {
		this.saveName = saveName;
	}
}