package com.dpc.model;

public class SysDict {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.DICT_KEY
	 * @mbggenerated
	 */
	private Long dictKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.DICT_VALUE
	 * @mbggenerated
	 */
	private String dictValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.TYPE_ID
	 * @mbggenerated
	 */
	private Long typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict.TYPE_NAME
	 * @mbggenerated
	 */
	private String typeName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.DICT_KEY
	 * @return  the value of sys_dict.DICT_KEY
	 * @mbggenerated
	 */
	public Long getDictKey() {
		return dictKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.DICT_KEY
	 * @param dictKey  the value for sys_dict.DICT_KEY
	 * @mbggenerated
	 */
	public void setDictKey(Long dictKey) {
		this.dictKey = dictKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.DICT_VALUE
	 * @return  the value of sys_dict.DICT_VALUE
	 * @mbggenerated
	 */
	public String getDictValue() {
		return dictValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.DICT_VALUE
	 * @param dictValue  the value for sys_dict.DICT_VALUE
	 * @mbggenerated
	 */
	public void setDictValue(String dictValue) {
		this.dictValue = dictValue == null ? null : dictValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.TYPE_ID
	 * @return  the value of sys_dict.TYPE_ID
	 * @mbggenerated
	 */
	public Long getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.TYPE_ID
	 * @param typeId  the value for sys_dict.TYPE_ID
	 * @mbggenerated
	 */
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict.TYPE_NAME
	 * @return  the value of sys_dict.TYPE_NAME
	 * @mbggenerated
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict.TYPE_NAME
	 * @param typeName  the value for sys_dict.TYPE_NAME
	 * @mbggenerated
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName == null ? null : typeName.trim();
	}
}