package com.dpc.model;

public class SysFileKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_file.ID
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_file.SAVE_NAME
	 * @mbggenerated
	 */
	private String saveName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_file.ID
	 * @return  the value of sys_file.ID
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_file.ID
	 * @param id  the value for sys_file.ID
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_file.SAVE_NAME
	 * @return  the value of sys_file.SAVE_NAME
	 * @mbggenerated
	 */
	public String getSaveName() {
		return saveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_file.SAVE_NAME
	 * @param saveName  the value for sys_file.SAVE_NAME
	 * @mbggenerated
	 */
	public void setSaveName(String saveName) {
		this.saveName = saveName == null ? null : saveName.trim();
	}
}