package com.dpc.model;


public class SysFile extends SysFileKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_file.REAL_NAME
	 * @mbggenerated
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_file.SAVE_PATH
	 * @mbggenerated
	 */
	private String savePath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_file.FILE_TYPE
	 * @mbggenerated
	 */
	private String fileType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_file.FILE_SIZE
	 * @mbggenerated
	 */
	private Long fileSize;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_file.REAL_NAME
	 * @return  the value of sys_file.REAL_NAME
	 * @mbggenerated
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_file.REAL_NAME
	 * @param realName  the value for sys_file.REAL_NAME
	 * @mbggenerated
	 */
	public void setRealName(String realName) {
		this.realName = realName == null ? null : realName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_file.SAVE_PATH
	 * @return  the value of sys_file.SAVE_PATH
	 * @mbggenerated
	 */
	public String getSavePath() {
		return savePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_file.SAVE_PATH
	 * @param savePath  the value for sys_file.SAVE_PATH
	 * @mbggenerated
	 */
	public void setSavePath(String savePath) {
		this.savePath = savePath == null ? null : savePath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_file.FILE_TYPE
	 * @return  the value of sys_file.FILE_TYPE
	 * @mbggenerated
	 */
	public String getFileType() {
		return fileType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_file.FILE_TYPE
	 * @param fileType  the value for sys_file.FILE_TYPE
	 * @mbggenerated
	 */
	public void setFileType(String fileType) {
		this.fileType = fileType == null ? null : fileType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_file.FILE_SIZE
	 * @return  the value of sys_file.FILE_SIZE
	 * @mbggenerated
	 */
	public Long getFileSize() {
		return fileSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_file.FILE_SIZE
	 * @param fileSize  the value for sys_file.FILE_SIZE
	 * @mbggenerated
	 */
	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}
}