package com.dpc.model;

public class SysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PERMISSION_ID
     *
     * @mbggenerated
     */
    private String permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PERMISSION_NAME
     *
     * @mbggenerated
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PARENT_ID
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PERMISSION_KEY
     *
     * @mbggenerated
     */
    private String permissionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PERMISSION_TYPE
     *
     * @mbggenerated
     */
    private String permissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PERMISSION_URL
     *
     * @mbggenerated
     */
    private String permissionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.PERMISSION_LEVEL
     *
     * @mbggenerated
     */
    private Long permissionLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PERMISSION_ID
     *
     * @return the value of sys_permission.PERMISSION_ID
     *
     * @mbggenerated
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PERMISSION_ID
     *
     * @param permissionId the value for sys_permission.PERMISSION_ID
     *
     * @mbggenerated
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PERMISSION_NAME
     *
     * @return the value of sys_permission.PERMISSION_NAME
     *
     * @mbggenerated
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PERMISSION_NAME
     *
     * @param permissionName the value for sys_permission.PERMISSION_NAME
     *
     * @mbggenerated
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PARENT_ID
     *
     * @return the value of sys_permission.PARENT_ID
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PARENT_ID
     *
     * @param parentId the value for sys_permission.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PERMISSION_KEY
     *
     * @return the value of sys_permission.PERMISSION_KEY
     *
     * @mbggenerated
     */
    public String getPermissionKey() {
        return permissionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PERMISSION_KEY
     *
     * @param permissionKey the value for sys_permission.PERMISSION_KEY
     *
     * @mbggenerated
     */
    public void setPermissionKey(String permissionKey) {
        this.permissionKey = permissionKey == null ? null : permissionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PERMISSION_TYPE
     *
     * @return the value of sys_permission.PERMISSION_TYPE
     *
     * @mbggenerated
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PERMISSION_TYPE
     *
     * @param permissionType the value for sys_permission.PERMISSION_TYPE
     *
     * @mbggenerated
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType == null ? null : permissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PERMISSION_URL
     *
     * @return the value of sys_permission.PERMISSION_URL
     *
     * @mbggenerated
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PERMISSION_URL
     *
     * @param permissionUrl the value for sys_permission.PERMISSION_URL
     *
     * @mbggenerated
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.PERMISSION_LEVEL
     *
     * @return the value of sys_permission.PERMISSION_LEVEL
     *
     * @mbggenerated
     */
    public Long getPermissionLevel() {
        return permissionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.PERMISSION_LEVEL
     *
     * @param permissionLevel the value for sys_permission.PERMISSION_LEVEL
     *
     * @mbggenerated
     */
    public void setPermissionLevel(Long permissionLevel) {
        this.permissionLevel = permissionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.DESCRIPTION
     *
     * @return the value of sys_permission.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.DESCRIPTION
     *
     * @param description the value for sys_permission.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}