package com.dpc.model;

public class SysPermissionRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_role.PERMISSION_ID
     *
     * @mbggenerated
     */
    private String permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission_role.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_role.PERMISSION_ID
     *
     * @return the value of sys_permission_role.PERMISSION_ID
     *
     * @mbggenerated
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_role.PERMISSION_ID
     *
     * @param permissionId the value for sys_permission_role.PERMISSION_ID
     *
     * @mbggenerated
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission_role.ROLE_ID
     *
     * @return the value of sys_permission_role.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission_role.ROLE_ID
     *
     * @param roleId the value for sys_permission_role.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}