package com.dpc.model;

public class SysRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.ROLE_ID
	 * @mbggenerated
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.ROLE_NAME
	 * @mbggenerated
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.ROLE_KEY
	 * @mbggenerated
	 */
	private String roleKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.DESCRIPTION
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.ROLE_ID
	 * @return  the value of sys_role.ROLE_ID
	 * @mbggenerated
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.ROLE_ID
	 * @param roleId  the value for sys_role.ROLE_ID
	 * @mbggenerated
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.ROLE_NAME
	 * @return  the value of sys_role.ROLE_NAME
	 * @mbggenerated
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.ROLE_NAME
	 * @param roleName  the value for sys_role.ROLE_NAME
	 * @mbggenerated
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.ROLE_KEY
	 * @return  the value of sys_role.ROLE_KEY
	 * @mbggenerated
	 */
	public String getRoleKey() {
		return roleKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.ROLE_KEY
	 * @param roleKey  the value for sys_role.ROLE_KEY
	 * @mbggenerated
	 */
	public void setRoleKey(String roleKey) {
		this.roleKey = roleKey == null ? null : roleKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.DESCRIPTION
	 * @return  the value of sys_role.DESCRIPTION
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.DESCRIPTION
	 * @param description  the value for sys_role.DESCRIPTION
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}