package com.dpc.model;

import java.util.Date;

public class SysUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.USER_ID
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.USER_NAME
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.PASSWORD
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.REAL_NAME
	 * @mbggenerated
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.SEX
	 * @mbggenerated
	 */
	private Long sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.POST
	 * @mbggenerated
	 */
	private Long post;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.RANK
	 * @mbggenerated
	 */
	private Long rank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.PHONE
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.MOBILE
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.EMAIL
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.CREDENTIALS_SALT
	 * @mbggenerated
	 */
	private String credentialsSalt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.DESCRIPTION
	 * @mbggenerated
	 */
	private String description;

	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.USER_ID
	 * @return  the value of sys_user.USER_ID
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.USER_ID
	 * @param userId  the value for sys_user.USER_ID
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.USER_NAME
	 * @return  the value of sys_user.USER_NAME
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.USER_NAME
	 * @param userName  the value for sys_user.USER_NAME
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.PASSWORD
	 * @return  the value of sys_user.PASSWORD
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.PASSWORD
	 * @param password  the value for sys_user.PASSWORD
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.REAL_NAME
	 * @return  the value of sys_user.REAL_NAME
	 * @mbggenerated
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.REAL_NAME
	 * @param realName  the value for sys_user.REAL_NAME
	 * @mbggenerated
	 */
	public void setRealName(String realName) {
		this.realName = realName == null ? null : realName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.SEX
	 * @return  the value of sys_user.SEX
	 * @mbggenerated
	 */
	public Long getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.SEX
	 * @param sex  the value for sys_user.SEX
	 * @mbggenerated
	 */
	public void setSex(Long sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.POST
	 * @return  the value of sys_user.POST
	 * @mbggenerated
	 */
	public Long getPost() {
		return post;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.POST
	 * @param post  the value for sys_user.POST
	 * @mbggenerated
	 */
	public void setPost(Long post) {
		this.post = post;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.RANK
	 * @return  the value of sys_user.RANK
	 * @mbggenerated
	 */
	public Long getRank() {
		return rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.RANK
	 * @param rank  the value for sys_user.RANK
	 * @mbggenerated
	 */
	public void setRank(Long rank) {
		this.rank = rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.PHONE
	 * @return  the value of sys_user.PHONE
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.PHONE
	 * @param phone  the value for sys_user.PHONE
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.MOBILE
	 * @return  the value of sys_user.MOBILE
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.MOBILE
	 * @param mobile  the value for sys_user.MOBILE
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.EMAIL
	 * @return  the value of sys_user.EMAIL
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.EMAIL
	 * @param email  the value for sys_user.EMAIL
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.CREATE_TIME
	 * @return  the value of sys_user.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.CREATE_TIME
	 * @param createTime  the value for sys_user.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.CREDENTIALS_SALT
	 * @return  the value of sys_user.CREDENTIALS_SALT
	 * @mbggenerated
	 */
	public String getCredentialsSalt() {
		return credentialsSalt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.CREDENTIALS_SALT
	 * @param credentialsSalt  the value for sys_user.CREDENTIALS_SALT
	 * @mbggenerated
	 */
	public void setCredentialsSalt(String credentialsSalt) {
		this.credentialsSalt = credentialsSalt == null ? null : credentialsSalt
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.DESCRIPTION
	 * @return  the value of sys_user.DESCRIPTION
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.DESCRIPTION
	 * @param description  the value for sys_user.DESCRIPTION
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
	
	/**
	 * For Form
	 */
	private String newPassword;
	private String newPasswordConfirm;
	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}

	public String getNewPasswordConfirm() {
		return newPasswordConfirm;
	}

	public void setNewPasswordConfirm(String newPasswordConfirm) {
		this.newPasswordConfirm = newPasswordConfirm;
	}
}