package com.dpc.dao;

import java.util.List;
import java.util.Map;

import com.dpc.model.DailyInfo;
import com.dpc.model.DailyInfoKey;

public interface DailyInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(DailyInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_info
	 * @mbggenerated
	 */
	int insert(DailyInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_info
	 * @mbggenerated
	 */
	int insertSelective(DailyInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_info
	 * @mbggenerated
	 */
	DailyInfo selectByPrimaryKey(DailyInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DailyInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DailyInfo record);

	List<DailyInfo> selectDailyInfoList(Map<String, Object> paraMap);
	
	int selectDailyInfoCount(Map<String, Object> paraMap);
}