package com.dpc.dao;

import java.util.List;
import java.util.Map;

import com.dpc.model.DailyReport;

public interface DailyReportMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_report
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String reportId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_report
	 * @mbggenerated
	 */
	int insert(DailyReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_report
	 * @mbggenerated
	 */
	int insertSelective(DailyReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_report
	 * @mbggenerated
	 */
	DailyReport selectByPrimaryKey(String reportId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_report
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DailyReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table daily_report
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DailyReport record);

	List<DailyReport> selectDailyReportList(Map<String, Object> paraMap);
	
	int selectDailyReportCount(Map<String, Object> paraMap);
}