package com.dpc.dao;

import java.util.List;
import java.util.Map;

import com.dpc.model.SysDict;

public interface SysDictMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long dictKey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict
	 * @mbggenerated
	 */
	int insert(SysDict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict
	 * @mbggenerated
	 */
	int insertSelective(SysDict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict
	 * @mbggenerated
	 */
	SysDict selectByPrimaryKey(Long dictKey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysDict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysDict record);

	List<SysDict> selectDictList(Map<String, Object> paraMap);
	
	List<SysDict> selectDictListByType(Long typeId);
}