package com.dpc.dao;

import java.util.List;

import com.dpc.model.SysFile;
import com.dpc.model.SysFileKey;

public interface SysFileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_file
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(SysFileKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_file
	 * @mbggenerated
	 */
	int insert(SysFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_file
	 * @mbggenerated
	 */
	int insertSelective(SysFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_file
	 * @mbggenerated
	 */
	SysFile selectByPrimaryKey(SysFileKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_file
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_file
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysFile record);

	List<SysFile> selectFileList(String id);
	
	int deleteBatch(String id);
}