package com.dpc.dao;

import com.dpc.model.SysPermissionRoleKey;

public interface SysPermissionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SysPermissionRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated
     */
    int insert(SysPermissionRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated
     */
    int insertSelective(SysPermissionRoleKey record);
}