package com.dpc.dao;

import java.util.List;
import java.util.Map;

import com.dpc.model.SysRole;

public interface SysRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String roleId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated
	 */
	int insert(SysRole record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated
	 */
	int insertSelective(SysRole record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated
	 */
	SysRole selectByPrimaryKey(String roleId);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysRole record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysRole record);
	List<SysRole> selectSysRoleList(Map<String, Object> paraMap);
	List<SysRole> selectSysRoleListByUserId(String userId);
}