package com.dpc.dao;

import com.dpc.model.SysUserRoleKey;

public interface SysUserRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(SysUserRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated
	 */
	int insert(SysUserRoleKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_role
	 * @mbggenerated
	 */
	int insertSelective(SysUserRoleKey record);
	
	int deleteUserRoleByUserid(String userid);
}