package com.dpc.dao;

import java.util.List;
import java.util.Map;

import com.dpc.model.TaskTest;

public interface TaskTestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_test
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_test
	 * @mbggenerated
	 */
	int insert(TaskTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_test
	 * @mbggenerated
	 */
	int insertSelective(TaskTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_test
	 * @mbggenerated
	 */
	TaskTest selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_test
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TaskTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table task_test
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TaskTest record);

	List<TaskTest> selectTaskTestList(Map<String, Object> paraMap);
	
	int selectTaskTestCount(Map<String, Object> paraMap);
}